baseURL= "/"
publishDir = "docs"
languageCode= "en"
title= "Fuzzy Dice"
paginate = 5
copyright = "All rights reserved - 2019"
theme = "hello-friend-ng"
disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [ "\\.foo$", "\\.boo$" ]
sectionPagesMenu = "main"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[blackfriday]
  angledQuotes = true
  hrefTargetBlank = true

[params]
    title = "Fuzzy Dice"
    date = "2019-10-03"
    description = "An experiment"
    # images = ["/images/social-share.jpg"]
    email = "hughlang@gmail.com"
    keywords = "ethereum, dice, games"
    copyright = ""
    cfpUrl = ""
    subscriptionUrl = ""
    # appleTouchIcon = "/apple-touch-icon.png"
    # favicon32 = "/favicon-32x32.png"
    # favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    # safariPinnedTab = "/safari-pinned-tab.svg"
    defaultTheme = "dark"

[params.logos]
    jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/devfest_color_text.png"
    footer = "/images/logos/devfest_gray_text.png"

[[menu.main]]
identifier = "login"
name = "Login"
url = "/login/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "help"
name = "Help"
url = "/help/"
weight = 3